version: "2.4"
services:
  openwrtbuilder:
    build:
      context: .
      network: host
    volumes:
      - ./:/usr/local/src/custom_firmware/
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
